{
	"Breadth": [
		{
			"attributes": null,
			"catalog_num": "303-0",
			"class_num": 12832,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5026,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158926,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Fatma Seda Memik",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have taken EECS 203-0 or be CE/CS/EE Graduate students in order to enroll.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 586,
				"name": "L150"
			},
			"school": "MEAS",
			"search_name": "EECS 303-0",
			"seats": 40,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Advanced Digital Design",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "330-0",
			"class_num": 12836,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 7098,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158931,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Michael Stephen Horn",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have completed EECS 211 or have graduate standing to enroll in this course.",
			"room": {
				"building_id": 39,
				"building_name": "Annenberg Hall",
				"id": 122,
				"name": "G21"
			},
			"school": "MEAS",
			"search_name": "EECS 330-0",
			"seats": 115,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Human Computer Interaction",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "332-0",
			"class_num": 12838,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5034,
			"end_date": "2017-12-02",
			"end_time": "12:20",
			"id": 158933,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Ying Wu",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-Req: Students must have taken EECS 214-0, IEMS 202-0, and MATH 240-0 in order to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 608,
				"name": "M177"
			},
			"school": "MEAS",
			"search_name": "EECS 332-0",
			"seats": 40,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Computer Vision",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "336-0",
			"class_num": 12839,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4980,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158934,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jason D Hartline",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Prerequisite: Students must have completed EECS 212-0 & EECS 214-0, or be Computer Science Graduate students in order to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 548,
				"name": "LR3"
			},
			"school": "MEAS",
			"search_name": "EECS 336-0",
			"seats": 100,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Design & Analysis of Algorithms",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "338-0",
			"class_num": 12840,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 15672,
			"end_date": "2017-12-02",
			"end_time": "21:00",
			"id": 158935,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Lawrence A Birnbaum",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Mo",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 550,
				"name": "LR5"
			},
			"school": "MEAS",
			"search_name": "EECS 338-0",
			"seats": 20,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "18:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Practicum in Intelligent Information Systems",
			"topic": null
		},
		{
			"attributes": "Prerequisites apply, see description\n\n",
			"catalog_num": "339-0",
			"class_num": 12841,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4982,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158936,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jennie M Rogers",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have completed EECS 214 & (213 or 205), or be CS Grad students (MS or PhD) in order to register for this course. Students must also be willing to learn the Java programming language and be comfortable working in a command line interface.",
			"room": {
				"building_id": 62,
				"building_name": "Frances Searle",
				"id": 222,
				"name": "2407"
			},
			"school": "MEAS",
			"search_name": "EECS 339-0",
			"seats": 55,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "16:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Database Systems",
			"topic": null
		},
		{
			"attributes": "Prerequisites apply, see description\n\n",
			"catalog_num": "343-0",
			"class_num": 12820,
			"component": "LEC",
			"course_components": [
				{
					"component": "DIS",
					"end_time": "18:50",
					"meeting_days": "We",
					"room": "Technological Institute L361",
					"section": "60",
					"start_time": "18:00"
				}
			],
			"course_descriptions": [],
			"course_id": 14803,
			"end_date": "2017-12-02",
			"end_time": "09:20",
			"id": 158937,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Fabian E Bustamante",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-requisite: Students must have completed EECS 213 and EECS 214 to enroll in this course.",
			"room": {
				"building_id": 39,
				"building_name": "Annenberg Hall",
				"id": 122,
				"name": "G21"
			},
			"school": "MEAS",
			"search_name": "EECS 343-0",
			"seats": 91,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "08:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Operating Systems",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "348-0",
			"class_num": 12842,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4986,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158938,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Kristian J Hammond",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have taken [EECS 111 and (EECS 214 or be a CogSci major)] or be a Computer Science PhD student, or obtain instructor permission, in order to register for this course.",
			"room": {
				"building_id": 116,
				"building_name": "Swift Hall",
				"id": 535,
				"name": "107"
			},
			"school": "MEAS",
			"search_name": "EECS 348-0",
			"seats": 100,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "12:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Artificial Intelligence",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "349-0",
			"class_num": 17406,
			"component": "LEC",
			"course_components": [
				{
					"component": "DIS",
					"end_time": "15:50",
					"meeting_days": "Fr",
					"room": "Technological Institute L168",
					"section": "63",
					"start_time": "15:00"
				}
			],
			"course_descriptions": [],
			"course_id": 8177,
			"end_date": "2017-12-02",
			"end_time": "16:20",
			"id": 162388,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Bryan A. Pardo",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": "Enrollment Requirements: Registration is reserved for Electrical Engineering, Computer Science, & Computer Engineering PHDs only\n\nPrerequisite: Students must have completed EECS 214-0 or EECS 325-1, or be Graduate students in order to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 591,
				"name": "L211"
			},
			"school": "MEAS",
			"search_name": "EECS 349-0",
			"seats": 15,
			"section": "21",
			"start_date": "2017-09-19",
			"start_time": "15:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Machine Learning",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "349-0",
			"class_num": 12822,
			"component": "LEC",
			"course_components": [
				{
					"component": "DIS",
					"end_time": null,
					"meeting_days": null,
					"room": "TBA",
					"section": "X62",
					"start_time": null
				},
				{
					"component": "DIS",
					"end_time": "15:50",
					"meeting_days": "Fr",
					"room": "Technological Institute L251",
					"section": "60",
					"start_time": "15:00"
				},
				{
					"component": "DIS",
					"end_time": "15:50",
					"meeting_days": "Fr",
					"room": "Technological Institute L221",
					"section": "61",
					"start_time": "15:00"
				},
				{
					"component": "DIS",
					"end_time": "15:50",
					"meeting_days": "Fr",
					"room": "Technological Institute M177",
					"section": "62",
					"start_time": "15:00"
				}
			],
			"course_descriptions": [],
			"course_id": 8177,
			"end_date": "2017-12-02",
			"end_time": "16:20",
			"id": 158939,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Bryan A. Pardo",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": "Enrollment Requirements: Registration is reserved for Electrical Engineering, Computer Science, & Computer Engineering Masters students only.\n\nPrerequisite: Students must have completed EECS 214-0 or EECS 325-1, or be Graduate students in order to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 591,
				"name": "L211"
			},
			"school": "MEAS",
			"search_name": "EECS 349-0",
			"seats": 80,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Machine Learning",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "361-0",
			"class_num": 12845,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5046,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158942,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Gokhan Memik",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 62,
				"building_name": "Frances Searle",
				"id": 222,
				"name": "2407"
			},
			"school": "MEAS",
			"search_name": "EECS 361-0",
			"seats": 55,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "12:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Computer Architecture I",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "394-0",
			"class_num": 12848,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4992,
			"end_date": "2017-12-02",
			"end_time": "12:20",
			"id": 158948,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Christopher K Riesbeck",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 606,
				"name": "M164"
			},
			"school": "MEAS",
			"search_name": "EECS 394-0",
			"seats": 56,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Software Project Management & Development",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "397-0",
			"class_num": 18868,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5073,
			"end_date": "2017-12-02",
			"end_time": "14:20",
			"id": 162745,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Brent Jaron Hecht",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "WeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 613,
				"name": "M349"
			},
			"school": "MEAS",
			"search_name": "EECS 397-0",
			"seats": 10,
			"section": "79",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects in Computer Science",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "397-0",
			"class_num": 17399,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5073,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 161570,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Haoqi Zhang",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 397-0",
			"seats": 60,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects in Computer Science",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "397-0",
			"class_num": 17417,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5073,
			"end_date": "2017-12-02",
			"end_time": "11:50",
			"id": 161578,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Marcelo Aaron Bonilla Worsley",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Fr",
			"overview": null,
			"requirements": null,
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 397-0",
			"seats": 15,
			"section": "76",
			"start_date": "2017-09-19",
			"start_time": "09:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects in Computer Science",
			"topic": "Inclusive Making"
		},
		{
			"attributes": null,
			"catalog_num": "397-0",
			"class_num": 17486,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5073,
			"end_date": "2017-12-02",
			"end_time": "16:20",
			"id": 161728,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Kristian J Hammond",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 60,
				"building_name": "Fisk Hall",
				"id": 178,
				"name": "111"
			},
			"school": "MEAS",
			"search_name": "EECS 397-0",
			"seats": 10,
			"section": "77",
			"start_date": "2017-09-19",
			"start_time": "14:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects in Computer Science",
			"topic": "Special Projects In COLLABORATIVE INNOVATION IN JO"
		}
	],
	"Depth": [
		{
			"attributes": null,
			"catalog_num": "301-0",
			"class_num": 12830,
			"component": "LAB",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 21360,
			"end_date": "2017-12-02",
			"end_time": "18:00",
			"id": 158924,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Brenna Dee Argall",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-Req: Students must have taken EECS 110-0 or EECS 111-0 or EECS 230-0 in order to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 546,
				"name": "CG50 (EECS T-Lab)"
			},
			"school": "MEAS",
			"search_name": "EECS 301-0",
			"seats": 24,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Robotics Laboratory",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 14402,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "10:50",
			"id": 158953,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Morteza Amir Rahimi",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 99,
				"building_name": "Parkes Hall",
				"id": 468,
				"name": "224"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 15,
			"section": "73",
			"start_date": "2017-09-19",
			"start_time": "09:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Tech Infrastructure: Concepts/Requirements/Dsgn/Op"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 12852,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158952,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Koray Aydin",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 574,
				"name": "F280"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 30,
			"section": "72",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Metamaterials and Plasmonics, and their Applicatio"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 18495,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "09:50",
			"id": 162489,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Ermin Wei",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Reserved for Graduate Students.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 606,
				"name": "M164"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 15,
			"section": "35",
			"start_date": "2017-09-19",
			"start_time": "09:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Probabilistic Systems and Random Signals"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 18415,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "10:50",
			"id": 162447,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jeremy Maurer Watt",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 612,
				"name": "M345"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 30,
			"section": "77",
			"start_date": "2017-09-19",
			"start_time": "09:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Optimization Techniques for Machine & Deep Learnin"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 17349,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 161522,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 15,
			"section": "76",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Inclusive Making"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 18823,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 162675,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Nicos Maglaveras",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 603,
				"name": "M120"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 14,
			"section": "71",
			"start_date": "2017-09-19",
			"start_time": "12:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Personal Health Systems"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 12850,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158950,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jie Gu",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 599,
				"name": "LG66"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 10,
			"section": "56",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Advanced Low Power Digital and Mixed-signal Integr"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 12851,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158951,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Hai Zhou",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 592,
				"name": "L221"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 30,
			"section": "58",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "The Art of Multicore Concurrent Programming"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 12849,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "21:00",
			"id": 158949,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Xin Chen",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Tu",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 20,
				"building_name": "555 Clark St",
				"id": 74,
				"name": "B01"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 20,
			"section": "34",
			"start_date": "2017-09-19",
			"start_time": "18:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Biometrics"
		},
		{
			"attributes": null,
			"catalog_num": "395-0",
			"class_num": 18414,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4994,
			"end_date": "2017-12-02",
			"end_time": "14:50",
			"id": 162448,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jeremy Maurer Watt",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 547,
				"name": "LR2"
			},
			"school": "MEAS",
			"search_name": "EECS 395-0",
			"seats": 90,
			"section": "78",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Deep Learning Foundations from Scratch"
		},
		{
			"attributes": null,
			"catalog_num": "469-0",
			"class_num": 12860,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 21363,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158961,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": "Enrollment Requirements: Reserved for Graduate Students.",
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 469-0",
			"seats": 25,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Machine Learning & Artificial Intelligence for Robotics",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "474-0",
			"class_num": 17374,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22301,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 161545,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Douglas C Downey",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have taken EECS 349-0 or be of Graduate standing in order to register for this course.",
			"room": {
				"building_id": 62,
				"building_name": "Frances Searle",
				"id": 211,
				"name": "1421"
			},
			"school": "MEAS",
			"search_name": "EECS 474-0",
			"seats": 30,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Probabilistic Graphical Models",
			"topic": null
		}
	],
	"Major": [
		{
			"attributes": "Social & Behavioral Sciences Distro Area\n\n",
			"catalog_num": "101-0",
			"class_num": 12785,
			"component": "LEC",
			"course_components": [
				{
					"component": "DIS",
					"end_time": "15:50",
					"meeting_days": "Fr",
					"room": "Tech Institute Lecture Room 5",
					"section": "60",
					"start_time": "15:00"
				},
				{
					"component": "DIS",
					"end_time": "15:50",
					"meeting_days": "Fr",
					"room": "Technological Institute LG72",
					"section": "61",
					"start_time": "15:00"
				},
				{
					"component": "DIS",
					"end_time": "13:50",
					"meeting_days": "Fr",
					"room": "Technological Institute L168",
					"section": "62",
					"start_time": "13:00"
				},
				{
					"component": "DIS",
					"end_time": "14:50",
					"meeting_days": "Fr",
					"room": "Technological Institute LG72",
					"section": "63",
					"start_time": "14:00"
				},
				{
					"component": "DIS",
					"end_time": "14:50",
					"meeting_days": "Fr",
					"room": "Technological Institute L168",
					"section": "64",
					"start_time": "14:00"
				},
				{
					"component": "DIS",
					"end_time": "13:50",
					"meeting_days": "Fr",
					"room": "Tech Institute Lecture Room 4",
					"section": "65",
					"start_time": "13:00"
				},
				{
					"component": "DIS",
					"end_time": "11:50",
					"meeting_days": "Fr",
					"room": "Technological Institute F280",
					"section": "66",
					"start_time": "11:00"
				},
				{
					"component": "DIS",
					"end_time": "11:50",
					"meeting_days": "Fr",
					"room": "Technological Institute L170",
					"section": "67",
					"start_time": "11:00"
				},
				{
					"component": "DIS",
					"end_time": "11:50",
					"meeting_days": "Fr",
					"room": "Technological Institute MG28",
					"section": "68",
					"start_time": "11:00"
				},
				{
					"component": "DIS",
					"end_time": "12:50",
					"meeting_days": "Fr",
					"room": "Technological Institute M120",
					"section": "69",
					"start_time": "12:00"
				},
				{
					"component": "DIS",
					"end_time": "13:50",
					"meeting_days": "Fr",
					"room": "No Room Needed",
					"section": "70",
					"start_time": "13:00"
				},
				{
					"component": "DIS",
					"end_time": "12:50",
					"meeting_days": "Fr",
					"room": "No Room Needed",
					"section": "71",
					"start_time": "12:00"
				},
				{
					"component": "DIS",
					"end_time": "10:50",
					"meeting_days": "Fr",
					"room": "Technological Institute M166",
					"section": "72",
					"start_time": "10:00"
				},
				{
					"component": "DIS",
					"end_time": "10:50",
					"meeting_days": "Fr",
					"room": "No Room Needed",
					"section": "73",
					"start_time": "10:00"
				},
				{
					"component": "DIS",
					"end_time": "15:50",
					"meeting_days": "Fr",
					"room": "Technological Institute LG62",
					"section": "74",
					"start_time": "15:00"
				},
				{
					"component": "DIS",
					"end_time": null,
					"meeting_days": null,
					"room": "TBA",
					"section": "X60",
					"start_time": null
				}
			],
			"course_descriptions": [],
			"course_id": 8093,
			"end_date": "2017-12-02",
			"end_time": "11:50",
			"id": 158910,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Christopher K Riesbeck",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 557,
				"name": "AUD"
			},
			"school": "MEAS",
			"search_name": "EECS 101-0",
			"seats": 350,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "An Introduction to Computer Science for Everyone",
			"topic": null
		},
		{
			"attributes": "Formal Studies Distro Area\n\n",
			"catalog_num": "111-0",
			"class_num": 12782,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4964,
			"end_date": "2017-12-02",
			"end_time": "12:50",
			"id": 158912,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Ian D Horswill",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 557,
				"name": "AUD"
			},
			"school": "MEAS",
			"search_name": "EECS 111-0",
			"seats": 350,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "12:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Fundamentals of Computer Programming",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "211-0",
			"class_num": 12783,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4967,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158915,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Sara Hodges Owsley",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have taken EECS 111-0 \"Fundamentals of Computer Programming\" to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 612,
				"name": "M345"
			},
			"school": "MEAS",
			"search_name": "EECS 211-0",
			"seats": 100,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "12:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Fundamentals of Computer Programming II",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "212-0",
			"class_num": 12784,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4968,
			"end_date": "2017-12-02",
			"end_time": "15:50",
			"id": 158916,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Aravindan Vijayaraghavan",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-requisites: (EECS 110 or EECS 111) and Math 230",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 595,
				"name": "L361"
			},
			"school": "MEAS",
			"search_name": "EECS 212-0",
			"seats": 60,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Mathematical Foundations of Comp Science",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "213-0",
			"class_num": 12808,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 15611,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158917,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Nikolaos Hardavellas",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-requisite: Students must have completed EECS 211 to enroll in this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 612,
				"name": "M345"
			},
			"school": "MEAS",
			"search_name": "EECS 213-0",
			"seats": 102,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Computer Systems",
			"topic": null
		}
	],
	"Other": [
		{
			"attributes": "Formal Studies Distro Area\n\n",
			"catalog_num": "110-0",
			"class_num": 12781,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4963,
			"end_date": "2017-12-02",
			"end_time": "10:50",
			"id": 158911,
			"instructor": {
				"address": "3.320 Ford Design Center, Room 3.341 2133 Sheridan Road Evanston, IL 60208",
				"bio": null,
				"name": "John E Tumblin",
				"office_hours": "contact Instructor",
				"phone": "847 4672129"
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 62,
				"building_name": "Frances Searle",
				"id": 211,
				"name": "1421"
			},
			"school": "MEAS",
			"search_name": "EECS 110-0",
			"seats": 65,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "10:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Computer Programming",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "202-0",
			"class_num": 12801,
			"component": "LEC",
			"course_components": [
				{
					"component": "LAB",
					"end_time": "17:50",
					"meeting_days": "Th",
					"room": "Technological Institute MG18",
					"section": "62",
					"start_time": "15:00"
				},
				{
					"component": "LAB",
					"end_time": "17:50",
					"meeting_days": "Fr",
					"room": "Technological Institute MG18",
					"section": "63",
					"start_time": "15:00"
				},
				{
					"component": "LAB",
					"end_time": "17:50",
					"meeting_days": "We",
					"room": "Technological Institute MG18",
					"section": "61",
					"start_time": "15:00"
				},
				{
					"component": "LAB",
					"end_time": "17:50",
					"meeting_days": "Tu",
					"room": "Technological Institute MG18",
					"section": "65",
					"start_time": "15:00"
				}
			],
			"course_descriptions": [],
			"course_id": 7103,
			"end_date": "2017-12-02",
			"end_time": "14:50",
			"id": 158913,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Allen Taflove",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 595,
				"name": "L361"
			},
			"school": "MEAS",
			"search_name": "EECS 202-0",
			"seats": 80,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Electrical Engineering",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "203-0",
			"class_num": 12806,
			"component": "LEC",
			"course_components": [
				{
					"component": "LAB",
					"end_time": null,
					"meeting_days": null,
					"room": "Technological Institute CG30",
					"section": "60",
					"start_time": null
				}
			],
			"course_descriptions": [],
			"course_id": 8643,
			"end_date": "2017-12-02",
			"end_time": "11:50",
			"id": 158914,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Russell E Joseph",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 595,
				"name": "L361"
			},
			"school": "MEAS",
			"search_name": "EECS 203-0",
			"seats": 90,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Computer Engineering",
			"topic": null
		},
		{
			"attributes": "Prerequisites apply, see description\n\n",
			"catalog_num": "214-0",
			"class_num": 12809,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4969,
			"end_date": "2017-12-02",
			"end_time": "10:50",
			"id": 158918,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jesse Adam Tov",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-Requisite: Students must have completed EECS 211-0 or obtain instructor permission to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 595,
				"name": "L361"
			},
			"school": "MEAS",
			"search_name": "EECS 214-0",
			"seats": 90,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "09:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Data Structures & Data Management",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "222-0",
			"class_num": 12810,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 7131,
			"end_date": "2017-12-02",
			"end_time": "14:50",
			"id": 158919,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Thrasyvoulos N Pappas",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 588,
				"name": "L160"
			},
			"school": "MEAS",
			"search_name": "EECS 222-0",
			"seats": 30,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Fundamentals of Signals & Systems",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "223-0",
			"class_num": 12811,
			"component": "LEC",
			"course_components": [
				{
					"component": "LAB",
					"end_time": "18:00",
					"meeting_days": "Mo",
					"room": "Technological Institute CG10",
					"section": "60",
					"start_time": "15:00"
				},
				{
					"component": "LAB",
					"end_time": "18:00",
					"meeting_days": "Tu",
					"room": "Technological Institute CG10",
					"section": "61",
					"start_time": "15:00"
				}
			],
			"course_descriptions": [],
			"course_id": 8645,
			"end_date": "2017-12-02",
			"end_time": "09:50",
			"id": 158920,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Pedram Khalili Amiri",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 597,
				"name": "LG52"
			},
			"school": "MEAS",
			"search_name": "EECS 223-0",
			"seats": 24,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "09:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Fundamentals of Solid State Engineering",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "224-0",
			"class_num": 12828,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 8646,
			"end_date": "2017-12-02",
			"end_time": "11:50",
			"id": 158921,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Allen Taflove",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Sutdents must have taken EECS 202-0 and EECS 221-0 in order to register for this course. Multivariable calculus + differential equations recommended.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 598,
				"name": "LG62"
			},
			"school": "MEAS",
			"search_name": "EECS 224-0",
			"seats": 20,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Fund of Electromagnetics & Photonics",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "225-0",
			"class_num": 12814,
			"component": "LEC",
			"course_components": [
				{
					"component": "LAB",
					"end_time": "20:50",
					"meeting_days": "Th",
					"room": "Technological Institute CG10",
					"section": "60",
					"start_time": "18:00"
				},
				{
					"component": "LAB",
					"end_time": "17:50",
					"meeting_days": "Th",
					"room": "Technological Institute CG10",
					"section": "61",
					"start_time": "15:00"
				}
			],
			"course_descriptions": [],
			"course_id": 8725,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158922,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Chi-Haur Wu",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 39,
				"building_name": "Annenberg Hall",
				"id": 111,
				"name": "101"
			},
			"school": "MEAS",
			"search_name": "EECS 225-0",
			"seats": 20,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Fundamentals of Electronics",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "295-0",
			"class_num": 12829,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 20520,
			"end_date": "2017-12-02",
			"end_time": "14:50",
			"id": 158923,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Robert Findler",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have completed EECS 111-0, but NOT yet completed EECS 211-0 in order to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 594,
				"name": "L251"
			},
			"school": "MEAS",
			"search_name": "EECS 295-0",
			"seats": 50,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "12:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Intermediate Topics in Electrical Engineering and Computer Science",
			"topic": "Intensive Program Design"
		},
		{
			"attributes": null,
			"catalog_num": "302-0",
			"class_num": 12831,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5025,
			"end_date": "2017-12-02",
			"end_time": "09:50",
			"id": 158925,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Ermin Wei",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have taken MATH 234-0 in order to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 606,
				"name": "M164"
			},
			"school": "MEAS",
			"search_name": "EECS 302-0",
			"seats": 35,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "09:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Probabilistic Systems and Random Signals",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "307-0",
			"class_num": 12817,
			"component": "LEC",
			"course_components": [
				{
					"component": "LAB",
					"end_time": "17:00",
					"meeting_days": "Fr",
					"room": "Tech Institute CG50 - EECS T-L",
					"section": "61",
					"start_time": "15:00"
				},
				{
					"component": "LAB",
					"end_time": "17:00",
					"meeting_days": "We",
					"room": "Tech Institute CG50 - EECS T-L",
					"section": "60",
					"start_time": "15:00"
				}
			],
			"course_descriptions": [],
			"course_id": 5028,
			"end_date": "2017-12-02",
			"end_time": "10:50",
			"id": 158927,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Michael L Honig",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoTuWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 586,
				"name": "L150"
			},
			"school": "MEAS",
			"search_name": "EECS 307-0",
			"seats": 32,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "10:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Communications Systems",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "317-0",
			"class_num": 12834,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4971,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158929,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Stephen Patrick Tarzia",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have taken EECS 230-0 or EECS 211-0 or be of Graduate standing in order to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 547,
				"name": "LR2"
			},
			"school": "MEAS",
			"search_name": "EECS 317-0",
			"seats": 150,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Data Management & Information Processing",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "325-1",
			"class_num": 12835,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 4975,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158930,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Christopher K Riesbeck",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must have taken EECS 110 or EECS 111 to register for this course.",
			"room": {
				"building_id": 39,
				"building_name": "Annenberg Hall",
				"id": 121,
				"name": "G15"
			},
			"school": "MEAS",
			"search_name": "EECS 325-1",
			"seats": 80,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Artificial Intelligence Programming",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "355-0",
			"class_num": 12843,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 16344,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158940,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "David C Zaretsky",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 552,
				"name": "A110"
			},
			"school": "MEAS",
			"search_name": "EECS 355-0",
			"seats": 30,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "ASIC and FPGA Design",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "359-0",
			"class_num": 12844,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5044,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158941,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Thrasyvoulos N Pappas",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 605,
				"name": "M152"
			},
			"school": "MEAS",
			"search_name": "EECS 359-0",
			"seats": 56,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Digital Signal Processing",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "379-0",
			"class_num": 12827,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5058,
			"end_date": "2017-12-02",
			"end_time": "17:50",
			"id": 158945,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Th",
			"overview": null,
			"requirements": null,
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 379-0",
			"seats": 8,
			"section": "61",
			"start_date": "2017-09-19",
			"start_time": "15:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Lasers and Coherent Optics",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "379-0",
			"class_num": 12825,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5058,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158943,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Seng-Tiong Ho",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 589,
				"name": "L168"
			},
			"school": "MEAS",
			"search_name": "EECS 379-0",
			"seats": 16,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "12:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Lasers and Coherent Optics",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "379-0",
			"class_num": 12826,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5058,
			"end_date": "2017-12-02",
			"end_time": "17:50",
			"id": 158944,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Tu",
			"overview": null,
			"requirements": null,
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 379-0",
			"seats": 8,
			"section": "60",
			"start_date": "2017-09-19",
			"start_time": "15:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Lasers and Coherent Optics",
			"topic": null
		},
		{
			"attributes": "Prerequisites apply, see description\n\n",
			"catalog_num": "381-0",
			"class_num": 12846,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5060,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 158946,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Hooman Mohseni",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 588,
				"name": "L160"
			},
			"school": "MEAS",
			"search_name": "EECS 381-0",
			"seats": 30,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Electronic Materials: Properties and Applications",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "384-0",
			"class_num": 12847,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5063,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158947,
			"instructor": {
				"address": "TECH 2145 Sheridan Rd L387",
				"bio": null,
				"name": "Matthew A Grayson",
				"office_hours": null,
				"phone": "847/491-8137"
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 601,
				"name": "LG72"
			},
			"school": "MEAS",
			"search_name": "EECS 384-0",
			"seats": 25,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Solid State Electronic Devices",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "396-0",
			"class_num": 12854,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22536,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158955,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Simone Campanoni",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-req: EECS 213 or permission from the instructor.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 547,
				"name": "LR2"
			},
			"school": "MEAS",
			"search_name": "EECS 396-0",
			"seats": 60,
			"section": "21",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Computer Science",
			"topic": "Code Analysis and Transformati"
		},
		{
			"attributes": null,
			"catalog_num": "396-0",
			"class_num": 12853,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22536,
			"end_date": "2017-12-02",
			"end_time": "15:50",
			"id": 158954,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Ian D Horswill",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-req: EECS 214 or graduate standing.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 547,
				"name": "LR2"
			},
			"school": "MEAS",
			"search_name": "EECS 396-0",
			"seats": 150,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Computer Science",
			"topic": "Game Design and Development"
		},
		{
			"attributes": null,
			"catalog_num": "396-0",
			"class_num": 18833,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22536,
			"end_date": "2017-12-02",
			"end_time": "12:20",
			"id": 162716,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jason Russell Wilson",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-requisite: Students must have taken EECS 348-0 or obtain permission from the instructor to enroll in this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 588,
				"name": "L160"
			},
			"school": "MEAS",
			"search_name": "EECS 396-0",
			"seats": 10,
			"section": "24",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Computer Science",
			"topic": "Affective Computing Seminar"
		},
		{
			"attributes": null,
			"catalog_num": "396-0",
			"class_num": 12855,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22536,
			"end_date": "2017-12-02",
			"end_time": "17:20",
			"id": 158956,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Huxley David Bennett",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-req: EECS 214 or graduate standing.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 606,
				"name": "M164"
			},
			"school": "MEAS",
			"search_name": "EECS 396-0",
			"seats": 60,
			"section": "22",
			"start_date": "2017-09-19",
			"start_time": "16:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Computer Science",
			"topic": "Computational Geometry"
		},
		{
			"attributes": null,
			"catalog_num": "396-0",
			"class_num": 12856,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22536,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158957,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Michael Rubenstein",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 574,
				"name": "F280"
			},
			"school": "MEAS",
			"search_name": "EECS 396-0",
			"seats": 0,
			"section": "23",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Computer Science",
			"topic": "Swarms and Multi-Robot Systems"
		},
		{
			"attributes": null,
			"catalog_num": "404-0",
			"class_num": 12857,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5079,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158958,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Selim M Shahriar",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 608,
				"name": "M177"
			},
			"school": "MEAS",
			"search_name": "EECS 404-0",
			"seats": 40,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Quantum Electronics",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "406-0",
			"class_num": 12858,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5081,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158959,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Prem Kumar",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 589,
				"name": "L168"
			},
			"school": "MEAS",
			"search_name": "EECS 406-0",
			"seats": 20,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Nonlinear Optics",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "410-0",
			"class_num": 12859,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5086,
			"end_date": "2017-12-02",
			"end_time": "11:50",
			"id": 158960,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Arthur Butz",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 62,
				"building_name": "Frances Searle",
				"id": 220,
				"name": "2370"
			},
			"school": "MEAS",
			"search_name": "EECS 410-0",
			"seats": 20,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "System Theory",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 18824,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "13:50",
			"id": 162676,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Nicos Maglaveras",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 603,
				"name": "M120"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 14,
			"section": "71",
			"start_date": "2017-09-19",
			"start_time": "12:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Personal Health Systems"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 17316,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "12:20",
			"id": 161511,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Peter I Scheuermann",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 62,
				"building_name": "Frances Searle",
				"id": 211,
				"name": "1421"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 43,
			"section": "75",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Introduction to Database Systems"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 18416,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "10:50",
			"id": 162449,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jeremy Maurer Watt",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 612,
				"name": "M345"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 70,
			"section": "77",
			"start_date": "2017-09-19",
			"start_time": "09:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Machine Learning/Optimization"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 18413,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "14:50",
			"id": 162450,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jeremy Maurer Watt",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 547,
				"name": "LR2"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 150,
			"section": "78",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Neural Networks - Deep Learning"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 17385,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 161571,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Elizabeth M Gerber",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 10,
			"section": "76",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Inclusive Making"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 12862,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158963,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jie Gu",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 599,
				"name": "LG66"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 15,
			"section": "56",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Adv Dig. and Mix-Sig. IC Dsgn"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 12863,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158964,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Hai Zhou",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 586,
				"name": "L150"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 20,
			"section": "58",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "The Art of Multicore Concurrent Programming"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 14403,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "10:50",
			"id": 158966,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Morteza Amir Rahimi",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 99,
				"building_name": "Parkes Hall",
				"id": 468,
				"name": "224"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 15,
			"section": "73",
			"start_date": "2017-09-19",
			"start_time": "09:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Tech Infrastructure: Concepts/Requirements/Dsgn/Op"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 17296,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "15:50",
			"id": 158967,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Haoqi Zhang",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Fr",
			"overview": null,
			"requirements": "Enrollment Requirements: REASON: Pre-registration is not allowed for this class. Please try again during regular registration.",
			"room": {
				"building_id": 62,
				"building_name": "Frances Searle",
				"id": 220,
				"name": "2370"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 15,
			"section": "74",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Design, technology, & research"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 12861,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "21:00",
			"id": 158962,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Xin Chen",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Tu",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 20,
				"building_name": "555 Clark St",
				"id": 74,
				"name": "B01"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 30,
			"section": "34",
			"start_date": "2017-09-19",
			"start_time": "18:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Biometrics"
		},
		{
			"attributes": null,
			"catalog_num": "495-0",
			"class_num": 12864,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5010,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158965,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Koray Aydin",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 574,
				"name": "F280"
			},
			"school": "MEAS",
			"search_name": "EECS 495-0",
			"seats": 10,
			"section": "72",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics in Electrical Engineering and Computer Science",
			"topic": "Metamaterials and Plasmonics, and their Applicatio"
		},
		{
			"attributes": null,
			"catalog_num": "496-0",
			"class_num": 12869,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22537,
			"end_date": "2017-12-02",
			"end_time": "16:00",
			"id": 158972,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Aravindan Vijayaraghavan",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Th",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 597,
				"name": "LG52"
			},
			"school": "MEAS",
			"search_name": "EECS 496-0",
			"seats": 35,
			"section": "50",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics Section in Computer Science",
			"topic": "Topics in Theoretical Machine Learning"
		},
		{
			"attributes": null,
			"catalog_num": "496-0",
			"class_num": 18425,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22537,
			"end_date": "2017-12-02",
			"end_time": "15:50",
			"id": 162456,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Anindya De",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Fr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 600,
				"name": "LG68"
			},
			"school": "MEAS",
			"search_name": "EECS 496-0",
			"seats": 15,
			"section": "51",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics Section in Computer Science",
			"topic": "Computational Complexity"
		},
		{
			"attributes": null,
			"catalog_num": "496-0",
			"class_num": 12865,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22537,
			"end_date": "2017-12-02",
			"end_time": "15:50",
			"id": 158968,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Ian D Horswill",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWeFr",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-req: EECS 214 or graduate standing.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 547,
				"name": "LR2"
			},
			"school": "MEAS",
			"search_name": "EECS 496-0",
			"seats": 60,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": "15:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics Section in Computer Science",
			"topic": "Game Design and Development"
		},
		{
			"attributes": null,
			"catalog_num": "496-0",
			"class_num": 12867,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22537,
			"end_date": "2017-12-02",
			"end_time": "17:20",
			"id": 158970,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Huxley David Bennett",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "MoWe",
			"overview": null,
			"requirements": "Enrollment Requirements: Registration is reserved for Electrical Engineering, Computer Science, & Computer Engineering Masters and PhD students only.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 606,
				"name": "M164"
			},
			"school": "MEAS",
			"search_name": "EECS 496-0",
			"seats": 60,
			"section": "22",
			"start_date": "2017-09-19",
			"start_time": "16:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics Section in Computer Science",
			"topic": "Computational Geometry"
		},
		{
			"attributes": null,
			"catalog_num": "496-0",
			"class_num": 18834,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22537,
			"end_date": "2017-12-02",
			"end_time": "12:20",
			"id": 162717,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jason Russell Wilson",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 588,
				"name": "L160"
			},
			"school": "MEAS",
			"search_name": "EECS 496-0",
			"seats": 10,
			"section": "24",
			"start_date": "2017-09-19",
			"start_time": "11:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics Section in Computer Science",
			"topic": "Affective Computing Seminar"
		},
		{
			"attributes": null,
			"catalog_num": "496-0",
			"class_num": 12866,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22537,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158969,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Simone Campanoni",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Students must be CS PHDs to register for this course.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 547,
				"name": "LR2"
			},
			"school": "MEAS",
			"search_name": "EECS 496-0",
			"seats": 60,
			"section": "21",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics Section in Computer Science",
			"topic": "Code Analysis and Transformation"
		},
		{
			"attributes": null,
			"catalog_num": "496-0",
			"class_num": 12868,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22537,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 158971,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Michael Rubenstein",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Reserved for Graduate Students.",
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 574,
				"name": "F280"
			},
			"school": "MEAS",
			"search_name": "EECS 496-0",
			"seats": 60,
			"section": "23",
			"start_date": "2017-09-19",
			"start_time": "14:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Topics Section in Computer Science",
			"topic": "Swarms and Multi-Robot Systems"
		},
		{
			"attributes": null,
			"catalog_num": "497-0",
			"class_num": 18869,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22538,
			"end_date": "2017-12-02",
			"end_time": "14:20",
			"id": 162746,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Brent Jaron Hecht",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "WeFr",
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 119,
				"building_name": "Technological Institute",
				"id": 613,
				"name": "M349"
			},
			"school": "MEAS",
			"search_name": "EECS 497-0",
			"seats": 10,
			"section": "79",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects Section in Computer Science",
			"topic": "Spatial Data Science and Spatial Computing"
		},
		{
			"attributes": null,
			"catalog_num": "497-0",
			"class_num": 18897,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22538,
			"end_date": "2017-12-02",
			"end_time": "15:20",
			"id": 162748,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Jason D Hartline",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Tu",
			"overview": null,
			"requirements": null,
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 497-0",
			"seats": 30,
			"section": "80",
			"start_date": "2017-09-19",
			"start_time": "13:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects Section in Computer Science",
			"topic": "Peer Grading"
		},
		{
			"attributes": null,
			"catalog_num": "497-0",
			"class_num": 17379,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22538,
			"end_date": "2017-12-02",
			"end_time": "14:00",
			"id": 161561,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Haoqi Zhang",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "We",
			"overview": null,
			"requirements": null,
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 497-0",
			"seats": 60,
			"section": "74",
			"start_date": "2017-09-19",
			"start_time": "12:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects Section in Computer Science",
			"topic": "Design, Technology, & Research"
		},
		{
			"attributes": null,
			"catalog_num": "497-0",
			"class_num": 17418,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22538,
			"end_date": "2017-12-02",
			"end_time": "11:50",
			"id": 161579,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Marcelo Aaron Bonilla Worsley",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "Fr",
			"overview": null,
			"requirements": null,
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 497-0",
			"seats": 10,
			"section": "76",
			"start_date": "2017-09-19",
			"start_time": "09:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects Section in Computer Science",
			"topic": "Inclusive Making"
		},
		{
			"attributes": null,
			"catalog_num": "497-0",
			"class_num": 17400,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22538,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 161572,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Haoqi Zhang",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 497-0",
			"seats": 60,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Special Projects Section in Computer Science",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "512-1",
			"class_num": 12870,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 18490,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158973,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Selim M Shahriar",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 512-1",
			"seats": 30,
			"section": "21",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Graduate Research Seminar",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "512-1",
			"class_num": 12872,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 18490,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158975,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Peter A Dinda",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 512-1",
			"seats": 30,
			"section": "23",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Graduate Research Seminar",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "512-1",
			"class_num": 12876,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 18490,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158979,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Lawrence Joseph Henschen",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 512-1",
			"seats": 30,
			"section": "27",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Graduate Research Seminar",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "512-1",
			"class_num": 12871,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 18490,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158974,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Alan Varteres Sahakian",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 512-1",
			"seats": 30,
			"section": "22",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Graduate Research Seminar",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "512-1",
			"class_num": 12873,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 18490,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158976,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Ming-Yang Kao",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 512-1",
			"seats": 30,
			"section": "24",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Graduate Research Seminar",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "512-1",
			"class_num": 12874,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 18490,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158977,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Kenneth D Forbus",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 512-1",
			"seats": 30,
			"section": "25",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Graduate Research Seminar",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "512-1",
			"class_num": 12875,
			"component": "SEM",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 18490,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158978,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Ian D Horswill",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 512-1",
			"seats": 30,
			"section": "26",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Graduate Research Seminar",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "545-0",
			"class_num": 12877,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5117,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158980,
			"instructor": {
				"address": "TECH 2145 Sheridan Rd L387",
				"bio": null,
				"name": "Matthew A Grayson",
				"office_hours": null,
				"phone": "847/491-8137"
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 545-0",
			"seats": 15,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Teaching Experience I",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "546-0",
			"class_num": 12878,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 5118,
			"end_date": "2017-12-02",
			"end_time": null,
			"id": 158981,
			"instructor": {
				"address": "TECH 2145 Sheridan Rd L387",
				"bio": null,
				"name": "Matthew A Grayson",
				"office_hours": null,
				"phone": "847/491-8137"
			},
			"meeting_days": null,
			"overview": null,
			"requirements": null,
			"room": {
				"building_id": 118,
				"building_name": "TBA",
				"id": 545,
				"name": ""
			},
			"school": "MEAS",
			"search_name": "EECS 546-0",
			"seats": 15,
			"section": "20",
			"start_date": "2017-09-19",
			"start_time": null,
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Teaching Experience II",
			"topic": null
		}
	],
	"Project": [
		{
			"attributes": null,
			"catalog_num": "315-0",
			"class_num": 12833,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22523,
			"end_date": "2017-12-02",
			"end_time": "14:00",
			"id": 158928,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Haoqi Zhang",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "We",
			"overview": null,
			"requirements": null,
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 315-0",
			"seats": 30,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "12:00",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Design, Technology, and Research",
			"topic": null
		},
		{
			"attributes": null,
			"catalog_num": "331-0",
			"class_num": 12837,
			"component": "LEC",
			"course_components": [],
			"course_descriptions": [],
			"course_id": 22525,
			"end_date": "2017-12-02",
			"end_time": "16:50",
			"id": 158932,
			"instructor": {
				"address": null,
				"bio": null,
				"name": "Oliver Strides Cossairt",
				"office_hours": null,
				"phone": null
			},
			"meeting_days": "TuTh",
			"overview": null,
			"requirements": "Enrollment Requirements: Pre-Req: Students must have taken EECS 211-0 or EECS 230-0 in order to register for this course.",
			"room": null,
			"school": "MEAS",
			"search_name": "EECS 331-0",
			"seats": 40,
			"section": "1",
			"start_date": "2017-09-19",
			"start_time": "15:30",
			"subject": "EECS",
			"taken": false,
			"term": "2017 Fall",
			"title": "Introduction to Computational Photography",
			"topic": null
		}
	]
}
